server:
  port: 8080

spring:
  h2:
    console:
      enabled: true

key:
  space: 106

message:
  space: 500

dictionary:
  length: 70

charset:
  length: 27

space:
  value: 26
  frequency: 19

alphabet:
  length: 26

url:
  ciphertext: "http://localhost:8081/api/cipher/mod"
  digraph: "http://localhost:8082/api/digraph"
  decipher: "http://localhost:8080/api/climb/plaintext"